icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
info_bg = "#FCFF00"
info_fg = "#232c31"
idle_bg = "#232c31"
idle_fg = "#EBEBEB"
good_bg = "#FF214E"
good_fg = "#232c31"
warning_bg = "#0EE9F7"
warning_fg = "#232c31"
critical_bg = "#0EE9F7"
critical_fg = "#232c31"
separator_bg = "auto"
separator_fg = "auto"

[[block]]
block = "music"
player = "rhythmbox"
buttons = ["prev", "play", "next"]
max_width = 30

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 60

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 60

[[block]]
block = "memory"
format_mem = "{Mug}GB/{MTg}GB"
format_swap = "{SUg}GB/{STg}GB"
display_type = "memory"
clickable = true
interval = 15
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 15
format = "%a %d/%m %R"

